### PR TITLE
reformatted code, updated source headers

### PR DESCRIPTION
**Pull request by LeTurt**
such commit, much change

### CODE REVIEW

**Comment by ZedPea** [comment]
yasssss queen

**Comment by brandonlehmann** [comment]
Nice work. Will test. You'll be in charge of this now :) lol

**Comment by brandonlehmann** [comment]
@LeTurt  You've got merge conflicts here -- blame @ZedPea  :)

**Comment by LeTurt** [comment]
OK, can someone give me some list of magic git tricks to do the merge? My git skills are limited to pretty basics.

I would prefer to just overwrite my local files with the conflicting ones from remote and then just re-run the formatting and check the header as needed. git pull upstream development, then clion merge conflicts, etc just ends up with files missing and stuff. I guess I should also rebase to make the commit tree solid. Googling this stuff gets me more confused about how to do this simple thing. plz sirs helps?

**Comment by ZedPea** [comment]
The easiest thing to do would probably be to delete your fork, re-fork development branch, re-run the formatter, and commit.

Otherwise, you could do:

`git remote add upstream git://github.com/turtlecoin/turtlecoin.git`
`git fetch upstream`
`git merge -s recursive -X theirs` # Not 100% on this one, it might be `ours` instead of `theirs`

Then re-run formatter.

**Pull request closed without merging**
