### PR TITLE
Port over karbo crypto, and some of aeon/monero's crypto (mainly slow hash)

### PR DESCRIPTION
**Pull request by ZedPea**
As suggested by aiwe, I ported over their crypto. I decided to port over aeon's slow hash as that will be more portable and easier to alter with future modifications.

The chain appears to sync from both fresh and from the top of the chain, though a full sync hasn't been done. I would assume as long as it can validate blocks from both algos we're good.

~~I also need to test mnemonic seeds as that changed a tiny bit, and that wallet passwords are still working.~~

Update: mnemonics work fine, wallet passwords work fine.

Regarding licenses - not sure what license header to use, some bits are karbo (but ported from monero), and some parts are aeon (but ported from monero).

I haven't actually tested if this helps rpi compilation as I don't have one.

### CODE REVIEW

**Comment by brandonlehmann** [comment]
License should attribute both group(s)

**Comment by ZedPea** [comment]
Ok, think I did the licenses correctly. Tests are broken, I don't get why they build on travis but not on my machine, maybe I am stupid :thinking:

**Comment by ZedPea** [comment]
Ok, it builds now :+1:

**Comment by RocksteadyTC** [comment]
.....no way

**Comment by RocksteadyTC** [comment]
is this what I think it is?

**Comment by crappyrules** [comment]
I'll give this a spin let me load up a pi

**Pull request merged**
