### PR TITLE
Default simplewallet mixin, simplewallet bug fixes

### PR DESCRIPTION
**Pull request by ZedPea**
Adds a default mixin of 3 to simplewallet. This is waived if the transaction is dust and cannot be sent without lowering it. This can of course be bypassed by compiling without the restrictions but is a good start to introducing a minimum.

Also fixes issues with being unable to send on testnet.

I couldn't find a way to easily go from a prefix to a string to print out the expected string, so for now it just prints out `TRTL`.

Also fixes windows crashing with "simplewallet.exe has stopped working" when you ctrl+c - it's doing this when exit(0) is called, not sure if this is intended behaviour or possibly something being cleared up calling terminate(), for now it is hacked around :disappointed:  

Also fixes being unable to connect to daemon sometimes on windows - was able to reproduce 100% in windows 7 VM but worked fine for soregums on I think windows 10... was just using 0.0.0.0 instead of 127.0.0.1.

### CODE REVIEW

**Comment by yamiM0NSTER** [comment]
Weird that address length is hardcoded 99 O_o

**Comment by bobbieltd** [comment]
I checked testnet mine2gether. Why aren’t there any payments on testnet pool ? It’s great to have a testnet to avoid unexpected issues.

**Comment by sumlnoether** [comment]
The Mine2Gether testnet pool is just to test the algorithm for the miner devs.

**Comment by ZedPea** [comment]
This wouldn't effect pool payments btw, because they are either using old simplewallet or walletd which doesn't have this issue. This is just for sending testnet TRTL to people without having to recompile.

**Comment by ZedPea** [comment]
Idk why the build is failing on some random files I haven't touched... it worked fine on both linux and windows when I built

**Pull request merged**
