### PR TITLE
[ENHANCEMENT] Add Support for CryptoNight Variant 2

### PR DESCRIPTION
**Pull request by brandonlehmann**
Adding definitions and underlying changes for

* cn_slow_hash_v2
* cn_lite_slow_hash_v2

Borrowed from https://github.com/monero-project/monero/blob/master/src/crypto/slow-hash.c

### CODE REVIEW

**Comment by brandonlehmann** [comment]
Ha! Aarch64 build. I figured I fat fingered something.

**Comment by brandonlehmann** [comment]
Based on the information I've found -- this is the final version as implemented by the Monero Project.

I've removed the WIP tag as I believe it's ready to go.

**Comment by RocksteadyTC** [comment]
?

**Comment by brandonlehmann** [comment]
Passed CI and two approvals. It’s only implemented in cryptotest binary.

**Comment by RocksteadyTC** [comment]
ah ok

**Pull request merged**
