### PR TITLE
Remove CryptoNoteCore dependency from WalletBackend

### PR DESCRIPTION
**Pull request by zpalmtree**
Shuffles a ton of files around (and makes some small changes) to allow not having to pull in CryptoNoteCore when compiling WalletBackend.

This allows us to remove a ton of code, if we want to just compile WalletBackend -- see <https://github.com/turtlecoin/turtlecoin/compare/development...zpalmtree:wallet-backend-only>

### CODE REVIEW

**Comment by zpalmtree** [comment]
It compiles now

**Comment by brandonlehmann** [comment]
> It compiles now

But does it run?

**Comment by zpalmtree** [comment]
Not tested yet, I meant to test transactions + PID's worked since I touched the transaction extra stuff.

**Comment by brandonlehmann** [comment]
> Not tested yet, I meant to test transactions + PID's worked since I touched the transaction extra stuff.

I'm not seeing any immediate issues but I'd like some additional confirmation since this shuffles tons of stuff around.

**Comment by zpalmtree** [comment]
> > Not tested yet, I meant to test transactions + PID's worked since I touched the transaction extra stuff.
> 
> I'm not seeing any immediate issues but I'd like some additional confirmation since this shuffles tons of stuff around.
Ya, still haven't got round to testing. Will try and do today. I think that's the only place there was any significant code change. Might have fluffed the extra nonce tags.

**Comment by zpalmtree** [comment]
I believe this should be fine to merge now.

**Pull request merged**
