### PR TITLE
WIP: No longer require .bin files to be stored

### PR DESCRIPTION
**Pull request by zpalmtree**
Needs testing.

Needs verification of how corruption is handled.

Should save a large amount of disk space. May want to consider automatically removing old .bin files for users who are unaware the change has occured?

### CODE REVIEW

**Comment by zpalmtree** [comment]
2d uptime

**Comment by brandonlehmann** [comment]
Conflicts :)

**Comment by ngeojiajun** [comment]
the existence of the .bin file is to enable bootstrap through the local storage. After this pr merged, there will be no way for user to bootstrap their node. So, dont merge this unless alternative way for bootstraping node is in place

**Comment by brandonlehmann** [comment]
Please rebase on top of current `development` branch.

**Comment by RocksteadyTC** [comment]
?

**Comment by zpalmtree** [comment]
> 
> 
> ?

Got stuck trying to handle the database being corrupt and not even being able to pop blocks to restore using the .bin files.

**Pull request closed without merging**
