### PR TITLE
print_bc functionality

### PR DESCRIPTION
**Pull request by yamiM0NSTER**
1. commit to test if output is correct

Any feedback, tips on improving and suggestions much appreciated.

In final version should solve #85

### CODE REVIEW

**Comment by SoreGums** [comment]
maybe could make sure major version is ascii like the rest?

image

**Comment by yamiM0NSTER** [comment]
Improved print_bc function:

Can be called to print info about 1 block header as following:
`print_bc 295000`
Can be called to print info about block headers in given range:
`print_bc 295000 296000`

Fixed issue where last block could not be printed.
Fixed issue where block 0 could not be printed.
Function should be ready to be used in JsonRpc if there is need for it in the future.

**Comment by RocksteadyTC** [comment]
@ZedPea I see the thumbs up, is this ready to go?

**Comment by ZedPea** [comment]
I've not tested I'm afraid, I just thumbs up everything I see that looks cool :heart: @RocksteadyTC

**Pull request merged**
