### PR TITLE
my changes

### PR DESCRIPTION
**Pull request by bytechcoin**
nice work

### CODE REVIEW

**Comment by rashedmyt** [comment]
not here buddy

**Comment by brandonlehmann** [comment]
@bytechcoin might want to push this to your repo instead of here :)

**Comment by bytechcoin** [comment]
hi guys,

sorry about that. i am a rookie in this github portal and i really dont
know how to upload my updated files into my repository.

i did it in my updated folder on ubuntu with "git add . " then "git commit
-m "my changes" and git push origin master" commands...

can you help me if i am wrong with this commands.

best wishes

Rashed Mohammed <notifications@github.com>, 10 Oca 2019 Per, 18:44
tarihinde şunu yazdı:

**Comment by zpalmtree** [comment]
Your changes are here <https://github.com/bytechcoin/bytechcoin/tree/master>
You might want to change the default branch to be master for your fork. You have also made some changes to the development branch.

**Comment by bytechcoin** [comment]
thanks for your help

zpalmtree <notifications@github.com>, 10 Oca 2019 Per, 20:57 tarihinde şunu
yazdı:

**Pull request closed without merging**
