### PR TITLE
Fix RocksDB GCC 8 related bugs and add decrement() method

### PR DESCRIPTION
**Pull request by cfabio**
Using a newer version of RocksDB fix GCC 8 related bugs (e.g. https://github.com/facebook/rocksdb/commit/dee95a1afc6c63515e7d94dec33acdb79638b6d7).
Empty decrement method in DatabaseBlockchainCache.cpp is needed because otherwise Boost (version 1.66.0) throws errors at compile time.

### CODE REVIEW

**Comment by ZedPea** [comment]
It looks like this might revert the previous changes to make the build default to AVX/AVX2 being disabled, which was preventing the binary from running on some older cpu's without those instructions, specifically in `external/rocksdb/CMakeLists.txt`, can you confirm?

The appveyor build also seems to be failing.

**Comment by cfabio** [comment]
Yes, now that I look at it external/rocksdb/CMakeLists.txt does not include the AVX switch anymore.

**Comment by yamiM0NSTER** [comment]
First of all boost 1.59 is the highest tested and non-problematic version that is supposed to work.
Secondly, what in the flying fuck am I looking at:
>  void decrement() {
>    // DO NOTHING
>    //--globalOutputIndex;
>  }

**Comment by cfabio** [comment]
Feel free to implement a better solution, without the decrement method turtlecoin does not compile at all.
Secondly, boost 1.59 is outdated, Fedora 28 for example ships version 1.66 and in the upcoming future others distros will too.

**Comment by brandonlehmann** [comment]
From my point of view a few things need addressed here.

* Re-add the AVX/AVX2 checks in the rocksdb CMakeLists.txt. This addressed a breaking change for a lot of users.
* Address the Windows build tests error(s). Without addressing this, this PR is unusable.

**Comment by krypt0x** [comment]
I am getting stuck with this issue as well. Is there any solution already?

**Comment by ZedPea** [comment]
A patch was merged last night to add gcc8 support, pull from master and try compiling again.

**Comment by RocksteadyTC** [comment]
What's the status of this PR?

**Comment by brandonlehmann** [comment]
This has been handled in @zedpea merge.

**Comment by RocksteadyTC** [comment]
Thanks @brandonlehmann

**Pull request closed without merging**
