### PR TITLE
Add ascii art on daemon startup and sync

### PR DESCRIPTION
**Pull request by ZedPea**
Ascii art is A E S TH E T I C

image

### CODE REVIEW

**Comment by ZedPea** [comment]
Looks nicer in windows imo

image

**Comment by SoreGums** [comment]
adjust the settings?
different font

**Comment by RocksteadyTC** [comment]
Any thoughts on doing an ascii art contest?

**Comment by ZedPea** [comment]
Yeah I like the idea, yami and turtle? already put some nice ones in #dev_general

**Comment by RocksteadyTC** [comment]
Merging for now, then we can replace when we do the contest. My logic is that people will see it, make note of it in the chat, then we can hit them with the `!tag contest` and have it tell them about the ascii contest and give the constraints/proportions.

**Comment by holytastyguacamole** [comment]
image

**Pull request merged**
