### PR TITLE
Add interactive dockerfile

### PR DESCRIPTION
**Pull request by scottjw**
Make it a bit easier to run with a Dockerfile!

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
We had one, developed by @michelangelo314 but I'm not sure what the current state of it is

**Comment by scottjw** [comment]
okay I'll drop the request.

**Comment by RocksteadyTC** [comment]
You're welcome to create your own or collaborate with him on it, I am sure he'd like the help as I haven't seen him around much.

**Comment by RocksteadyTC** [comment]
This did not need to be closed, by the way. I was just offering commentary that maybe you guys could collab, but if yours is done and he's absent, I don't see why not.

**Pull request merged**
