### PR TITLE
[ENHANCEMENT] Activates Legacy Node Blocking

### PR DESCRIPTION
**Pull request by brandonlehmann**
***Do not merge this until after the release of 0.8.3*** to avoid all temptation of building 0.8.3 from a commit that includes this. I have opened this PR so we don't forget to do it.

5yvrecm

### CODE REVIEW

**Comment by zpalmtree** [comment]
I am running this commit so hard when 0.8.3 is out

**Comment by RocksteadyTC** [comment]
amused

**Comment by RocksteadyTC** [comment]
image

**Comment by brandonlehmann** [comment]
Not yet. Lol.

**Comment by brandonlehmann** [comment]
Rebased to current development head

**Comment by zpalmtree** [comment]
Merge time?

**Comment by brandonlehmann** [comment]
👋

**Pull request merged**
