### PR TITLE
Update encode script

### PR DESCRIPTION
**Pull request by Watt3r**

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
shouldn't anonymity come out and autodetect it from the network?

**Comment by brandonlehmann** [comment]
It only becomes an *optional* parameter with 0.8.3-RC if I recall -- until then it must be specified.

**Comment by zpalmtree** [comment]
True, but we've got to update it at some point, and this seems like a good time - the people running this script are probably also running dev

**Comment by brandonlehmann** [comment]
I came the the conclusion that we were discussing this script a lot more than we should be. lol

**Comment by zpalmtree** [comment]
touché

**Pull request merged**
