### PR TITLE
Reuse daemon connections in miner and zedwallet-beta

### PR DESCRIPTION
**Pull request by zpalmtree**
Easy way to verify that the miner/zedwallet-beta are only using one connection to communicate with the daemon:

```
lsof -i -a -p `pidof miner` -r1
```

If you turn on log level 4 in the daemon, you can also see when a new connection is created. This should occur only once.

This also changes the miner to use cpp-httplib.

### CODE REVIEW

**Comment by zpalmtree** [comment]
Oh, I need to make sure this works on Windows (if it even compiles) before merging.

**Comment by brandonlehmann** [comment]
@zpalmtree was Windows tested?

**Comment by zpalmtree** [comment]
Not yet. Let me spin up a VM.

**Comment by zpalmtree** [comment]
Seems to work. If Resource Monitor is to be believed, it's also reusing the same connection. And wow, I see how long it takes for a connection to be freed in there. Over a minute to free the socket after closing the program.

**Comment by zpalmtree** [comment]
OK. Think we're good to merge again if this builds.

**Pull request merged**
