### PR TITLE
zedwallet UI tweaks, cross platform linenoise

### PR DESCRIPTION
**Pull request by zpalmtree**
Makes the open menu, and 'TurtleCoind not open' menu match the standard number/command menu. All menus now have linenoise support, and future menus are far easier to implement.

Replaces linenoise with [cpp-linenoise](https://github.com/yhirose/cpp-linenoise) which provides a nicer API, has Windows support, fixes ctrl+c not working, and more.

I have tested on both Linux and Windows. If someone could test on Mac, that would be great.

### CODE REVIEW

**Comment by zpalmtree** [comment]
Screenshot 
image

Lovely consistency :blush:

**Comment by brandonlehmann** [comment]
Did ya test on ARM?

**Comment by zpalmtree** [comment]
Many hours later, it is still compiling

**Comment by brandonlehmann** [comment]
lol

**Comment by brandonlehmann** [comment]
i suppose... you could use the same directions travis uses to build on something else then test lol

**Comment by zpalmtree** [comment]
Don't get all fancy on me

**Comment by RocksteadyTC** [comment]
image

**Pull request merged**
