### PR TITLE
Fixes for serializations

### PR DESCRIPTION
**Pull request by ngeojiajun**
Fixed a wrong serialization of uint64_t by prepending it using '+'.
Note: Only serialization part have been checked.

### CODE REVIEW

**Comment by brandonlehmann** [comment]
Adding a plus to a number is not fixing the serialization issue as positive numbers do not have a plus sign in front of them.

**Comment by ngeojiajun** [comment]
Yeah, i forgot that i accidentally updated the rocksdb

**Comment by brandonlehmann** [comment]
Please roll that out of this. 

Rocksdb upgrades require that all the specified options that we’ve changed are carried through and handled separately.

**Comment by ngeojiajun** [comment]
I will close this because i need to refork the repo

**Comment by brandonlehmann** [comment]
Thanks. Let us know if you have any further questions.

**Pull request closed without merging**
