### PR TITLE
Fix fork heights being ill formed when empty

### PR DESCRIPTION
**Pull request by zpalmtree**
Previously if the fork heights array was empty, we would be allocating an array of 0 size, which is technically not supported behaviour. Most compilers don't complain, but I got a report of this failing in MSVC. So, we can use a std::initializer_list instead.

### CODE REVIEW

**Comment by zpalmtree** [comment]
Well, this compiles, but it needed me to use `Visual Studio 2017 Preview` instead of `Visual Studio 2017` in appveyor. I'm not sure how often they update their images, and if this fix is in the mainline Visual Studio. We probably don't want people having to install the preview version to get the code compiling. Would be good if someone could test.

More info: https://developercommunity.visualstudio.com/content/problem/62652/cant-declare-constexpr-initializer-list.html

**Comment by brandonlehmann** [comment]
I'm getting mixed results here.

This seems like an error caused by not following the fork guide correctly or that the fork guide does not explicitly explain. I'm not sure it's a good idea to push build environment updates for something so small that can be fixed by updating the fork guide (if required).

**Comment by zpalmtree** [comment]
No, it's not an error with the fork guide. It's perfectly legal to not have any upgrade heights, but the current code makes that not compile on Windows, since the array is zero sized. It compiles on Linux fine. We shouldn't force the user to have upgrade heights if they don't want any.

**Comment by brandonlehmann** [comment]
Tell me again why we can't use a `std::vector`?

**Comment by zpalmtree** [comment]
Not a constexpr

**Comment by brandonlehmann** [comment]
Can't we just put a 0 in the array? lol

**Comment by zpalmtree** [comment]
I guess....

**Comment by zpalmtree** [comment]
We're already requiring a pretty new VS for C++17 - Why not just leave this open till it's in mainline VS, rather than hacking around it?

**Comment by brandonlehmann** [comment]
Because @RocksteadyTC comes through randomly and clicks merge on PRs... :)

**Comment by RocksteadyTC** [comment]
come on now

**Comment by brandonlehmann** [comment]
Checking license headers now to make sure that's legit.

**Comment by RocksteadyTC** [comment]
I see green checks. JS

**Comment by brandonlehmann** [comment]
Leaving open until mainline VS supports this...

**Comment by RocksteadyTC** [comment]
?

**Comment by brandonlehmann** [comment]
Holding still.

**Comment by zpalmtree** [comment]
:weary:

**Pull request closed without merging**
