### PR TITLE
Improve the conciseness of the output json

### PR DESCRIPTION
**Pull request by zpalmtree**

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
yiss

**Comment by zpalmtree** [comment]
how fast

**Comment by RocksteadyTC** [comment]
very fast

**Comment by brandonlehmann** [comment]
Freaky fast?

**Comment by brandonlehmann** [comment]
Awe. Built tests failed.

**Comment by zpalmtree** [comment]
No more than they were failing before

**Comment by brandonlehmann** [comment]
Fix em. Maybe yami can help.

**Comment by zpalmtree** [comment]
I don't want to :(

**Comment by RocksteadyTC** [comment]
yami hates us

**Pull request merged**
