### PR TITLE
Add fork readyness info to status command

### PR DESCRIPTION
**Pull request by ZedPea**
* Tells the user if they need to upgrade for the fork or not
* Tells the user if the fork has already happened, and to upgrade if it has and they are not ready.
* Adds an easy mechanism to add new forks and indicate the current softwares fork support: Add a value to FORK_HEIGHTS, and increase the value of CURRENT_FORK_INDEX by one.

E.g: 
```
Height: 516685/516696 (99.99%) on mainnet, syncing, net hash 4.57 MH/s, v4 (next fork in 28.0 days) (Your version of the software is ready for this fork), 2(out)+0(in) connections, uptime 0d 0h 0m 4s
```

or
```
Height: 516685/516696 (99.99%) on mainnet, syncing, net hash 4.57 MH/s, v4 (next fork in 28.0 days) (Your software will need to be upgraded to support this fork), 2(out)+0(in) connections, uptime 0d 0h 0m 4s
```
or

```
Height: 516685/516696 (99.99%) on mainnet, syncing, net hash 4.57 MH/s, v4 (The network forked at height 350000, please update your software: https://turtlecoin.lol), 2(out)+0(in) connections, uptime 0d 0h 0m 4s
```

The git commits are a bit ugly on this because I had to revert the reverting of the PR :stuck_out_tongue:

### CODE REVIEW

**Comment by thinkpol2** [comment]
My only observation is that this is making the status line too long to actually fit on a line. Could the long upgrade message be separated from the status line, giving it a condensed version? a la Monero etc.

```
Height: 516685/516696 (99.99%) on mainnet, syncing, net hash 4.57 MH/s, v4 (next fork in 28.0 days), up to date, 2(out)+0(in) connections, uptime 0d 0h 0m 4s
```
```
Height: 516685/516696 (99.99%) on mainnet, syncing, net hash 4.57 MH/s, v4 (next fork in 28.0 days), update needed, 2(out)+0(in) connections, uptime 0d 0h 0m 4s
```

Extended messages print at startup and periodically as their own line:
```
2018-Jun-07 08:02:59.166311 INFO    Your software will need to be upgraded to support this fork. Please visit https://turtlecoin.lol.
```

**Comment by ZedPea** [comment]
This is a good idea, though printing at startup is a bit tricksy - we need to wait to get the correct remote node block height for the info to be correct, which usually takes at least 10 seconds after launching.

Not sure if we should just put the extra info on a separate line, as when you condense it that much it's a little unclear - Just `update needed` suggests an update is needed now, but if we just forked there will be no software available to handle the fork yet.

**Comment by thinkpol2** [comment]
Ah, note that "update needed" is triggered *before* the fork. There are 3 states (borrowing this from Monero):
```
up to date
update needed
out of date, likely forked
```

**Comment by ZedPea** [comment]
Currently it will only report up to date if you are ready for ALL for the forks listed in CryptoNoteConfig, so that's unlikely to happen. Perhaps it would be better to say up to date until N days before the fork, as there will be no software ready for them to upgrade to.

**Comment by thinkpol2** [comment]
I think that's a good idea. Now, how long before the fork does it warn you?

**Comment by ZedPea** [comment]
Lets see your version of the software supports the fork at 600k, provided you are < 600k, it will say 
`(Your version of the software is ready for this fork)`

As soon as you hit 600001, and there's another fork (in this case at 700k) it will say

`(Your software will need to be upgraded to support this fork)`

It will only display the `(The network forked at height 350000, please update your software: https://turtlecoin.lol)` message if your software doesn't support a fork height that the network has passed.

The framework is there, so if you want to make a PR to my fork i'll accept it ;)

**Comment by thinkpol2** [comment]
I'll see what I can put together. Thank you.

**Comment by ZedPea** [comment]
Ok, how does this look?

If the next fork is >25k blocks away or there are no more forks to come:
```
Height: 518804/518804 (100.00%) on mainnet, synced, net hash 9.21 MH/s, v4, up to date, 7(out)+1(in) connections, uptime 0d 0h 4m 2s
```

Next fork <25k blocks away, client updated:
```
Height: 518826/518826 (100.00%) on mainnet, synced, net hash 11.70 MH/s, v4, (next fork in 3.0 days), up to date, 2(out)+0(in) connections, uptime 0d 0h 0m 6s
```

Next fork <25k blocks away, client unupdated:
```
Height: 518810/518810 (100.00%) on mainnet, synced, net hash 7.82 MH/s, v4, (next fork in 3.0 days), update needed, 2(out)+0(in) connections, uptime 0d 0h 0m 6s
```

Client is out of date:
```
Height: 518827/448713 (100.00%) on mainnet, syncing, net hash 10.15 MH/s, v4, out of date, likely forked, 0(out)+2(in) connections, uptime 0d 0h 0m 13s
The network forked at height 350000, please update your software: https://turtlecoin.lol
```

**Comment by ZedPea** [comment]
Code is a bit over-engineered but it does the job.

**Pull request merged**
