### PR TITLE
Rework status command

### PR DESCRIPTION
**Pull request by zpalmtree**
image

### CODE REVIEW

**Comment by 0des** [comment]
Is this expanded to two columns horizontally when the terminal dimensions allow for it?

**Comment by zpalmtree** [comment]
> Is this expanded to two columns horizontally when the terminal dimensions allow for it?

No, I'm not aware of a cross platform way to query terminal info - and frankly, I think it probably looks better kept as one column?

**Comment by 0des** [comment]
Thank you.

**Comment by wrkzdev** [comment]
I like this one :)

**Comment by wrkzdev** [comment]
Can we have tx pool in `status` also?

**Comment by zpalmtree** [comment]
> Can we have tx pool in `status` also?

Just the number of transactions in the pool?

**Comment by zpalmtree** [comment]
Added the number of transactions in the pool to the table.

**Pull request merged**
