### PR TITLE
[WIP] RingCT

### PR DESCRIPTION
**Pull request by Amity-Core**
A basic implementation of RingCT. It compiles under Ubuntu 18.04.

This still needs work doing to it but as it is 5am here, im off to sleep. Maybe someone can be able to work on this

### CODE REVIEW

**Comment by zpalmtree** [comment]
Again, this adds the code, but doesn't hook it up - which is the hard bit I'm afraid.

**Comment by brandonlehmann** [comment]
And not passing build tests.

**Comment by RocksteadyTC** [comment]
??

**Comment by Amity-Core** [comment]
I'm working on something for AmityCoin at the moment as that need improvements itself. I am slowly trying to solve this in a local edit of TurtleCoin, that's why you're not seeing no progress on GitHub.

**Comment by brandonlehmann** [comment]
Closing pull request for the time being as this is *project* is tracked in https://github.com/turtlecoin/meta/issues/93

**Pull request closed without merging**
