### PR TITLE
Apply consistent formatting across the code base

### PR DESCRIPTION
**Pull request by brandonlehmann**
`clang-format -i -style="{ColumnLimit: 120,IndentWidth: 4,BreakBeforeBraces: Allman}"`

### CODE REVIEW

**Comment by michael-herwig** [comment]
Cannot see whether you supplied a `.clang-format` file (my browser literally hangs viewing the changes :D), many editors can be set up to search for that automatically in the source directory and apply it automatically.

**Comment by brandonlehmann** [comment]
I did not yet. I figured this would cause debate, anger, and ultimately negotiations.

**Comment by brandonlehmann** [comment]
Should have probably test compiled first :)

**Comment by brandonlehmann** [comment]
Those build errors are soooo angry

**Pull request closed without merging**
