### PR TITLE
Add status command to simplewallet

### PR DESCRIPTION
**Pull request by thinkpol2**
Adds the new status command to simplewallet. Consolidates common string functions related to status command to reduce code duplication. Cosmetic updates to fork countdown.

### CODE REVIEW

**Comment by ZedPea** [comment]
This is neat.

Regarding the simplewallet license changes, it's written from scratch by the TurtleCoin team, so doesn't necessarily need the bytecoin/cryptonote section in there, but if you want to keep it like that to make it uniform across the codebase that's fine too.

**Comment by thinkpol2** [comment]
Oops, didn't mean to leave Bytecoin in there.

**Comment by ZedPea** [comment]
Had a thought, what happens if simplewallet is updated but TurtleCoind isn't, for example if someone is using an unupdated remote node? Is the output still nice?

**Comment by thinkpol2** [comment]
Ehh, not exactly:
```
Height: 515435/515435 (100.00%) on mainnet, synced, net hash 7.44 MH/s, v192 (next fork in 48772276224.0 days), 5(out)+0(in) connections, uptime 17688d 20h 11m 39s
```

With an out-of-date daemon, simplewallet is not getting mainnet/testnet, block version, fork info, or daemon start time from the RPC server. It is however passing PROJECT_VERSION, so I could add a check based on that.

**Comment by brandonlehmann** [comment]
Are there other public nodes ? Lol. I usually update faster than everybody else. :)

**Comment by ZedPea** [comment]
I think blocks.turtle.link is still running? Doesn't hurt to cover all possibilities though ;)

**Pull request merged**
