### PR TITLE
Replace wallet saving/loading with rapidjson library

### PR DESCRIPTION
**Pull request by zpalmtree**
Resolves: #705 

For the upsides, see #705 

Downsides: Extra code, now we have two JSON libraries.
It shouldn't be *too* much effort to replace the rest of the code with rapidjson.

However, rapidjson has a much less friendly interface, easier to make mistakes serializing, and requires a few template classes just to make just getting a value out of it streamlined.

Most data we currently return with nlohmann from the wallet-api is pretty lightweight, but others could potentially grow pretty large, for example, getting all transactions in a large container.

These would certainly benefit from using rapidjson.

So, unsure if we should selectively use rapidjson where needed, or get rid of nlohmann json and deal with the worse API everywhere.

### CODE REVIEW

**Comment by brandonlehmann** [comment]
Cmake macro is wrong :(

**Comment by zpalmtree** [comment]
It's correct, but I guess these Cmake versions don't support it.

**Comment by brandonlehmann** [comment]
I got u fam

**Comment by brandonlehmann** [comment]
Windows error that one isn't a CMake one :(

**Comment by zpalmtree** [comment]
Compiles now. Windows.h macro fuckery.

**Comment by zpalmtree** [comment]
Don't merge yet, wallet sync status is not saving correctly

**Comment by zpalmtree** [comment]
Should be good to merge now.

**Pull request merged**
