### PR TITLE
Add support for Cryptonight v6, Cryptonight-Light v0 and their variant 1 versions. Add block major version 4 for proof of work hard fork.

### PR DESCRIPTION
**Pull request by sumlnoether**

### CODE REVIEW

**Comment by sumlnoether** [comment]
Suggested change to cryptonight-lite v1.

https://github.com/turtlecoin/meta/issues/74

**Comment by ZedPea** [comment]
Not compiling on windows due to unistd.h being missing

**Comment by bobbieltd** [comment]
&sumlnoether Could you explain what the purpose of your changes is ? Will turtlecoin change Monero v7 algo ? The copyright should credit to Monero too.

**Comment by sumlnoether** [comment]
@bobbieltd you need to learn how to comprehend things.

https://github.com/turtlecoin/turtlecoin/pull/119/commits/b8fad5311755eb8aaec29c76d585cb0537590295

**Comment by RocksteadyTC** [comment]
Thank you, @sumlnoether

**Pull request merged**
