### PR TITLE
Update to latest version of RocksDB (5.14.2)

### PR DESCRIPTION
**Pull request by ZedPea**
@brandonlehmann :wink: 

This might be placebo/faster internet, but I was getting blocks added way faster than normal.

### CODE REVIEW

**Comment by brandonlehmann** [comment]
Failing CI tests. Nice try :)

**Comment by RocksteadyTC** [comment]
```  28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(988): error C2065: 'STORAGE_PROPERTY_QUERY': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(988): error C2146: syntax error: missing ';' before identifier 'spropertyquery' [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(988): error C2065: 'spropertyquery': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(989): error C2065: 'spropertyquery': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(989): error C2228: left of '.PropertyId' must have class/struct/union [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(989): note: type is 'unknown-type'
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(989): error C2065: 'StorageAccessAlignmentProperty': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(990): error C2065: 'spropertyquery': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(990): error C2228: left of '.QueryType' must have class/struct/union [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(990): note: type is 'unknown-type'
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(990): error C2065: 'PropertyStandardQuery': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(992): error C2065: 'STORAGE_ACCESS_ALIGNMENT_DESCRIPTOR': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(995): error C2065: 'IOCTL_STORAGE_QUERY_PROPERTY': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(996): error C2065: 'spropertyquery': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(997): error C2065: 'STORAGE_ACCESS_ALIGNMENT_DESCRIPTOR': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1000): error C2065: 'STORAGE_ACCESS_ALIGNMENT_DESCRIPTOR': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1000): error C2059: syntax error: ')' [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1005): error C2065: 'DISK_GEOMETRY_EX': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1005): error C2146: syntax error: missing ';' before identifier 'geometry' [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1005): error C2065: 'geometry': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1006): error C2065: 'IOCTL_DISK_GET_DRIVE_GEOMETRY': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1007): error C2065: 'geometry': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1009): error C2065: 'geometry': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1009): error C2228: left of '.Geometry' must have class/struct/union [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1009): note: type is 'unknown-type'
    28>c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1009): error C2228: left of '.BytesPerSector' must have class/struct/union [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         port_win.cc
         win_logger.cc
         win_thread.cc
    28>Done Building Project "C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj" (default targets) -- FAILED.
    10>Done Building Project "C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj.metaproj" (default targets) -- FAILED.
     2>Done Building Project "C:\projects\turtlecoin\build\ALL_BUILD.vcxproj.metaproj" (default targets) -- FAILED.
     1>Done Building Project "C:\projects\turtlecoin\build\TurtleCoin.sln" (default targets) -- FAILED.
Build FAILED.
       "C:\projects\turtlecoin\build\TurtleCoin.sln" (default target) (1) ->
       "C:\projects\turtlecoin\build\src\zedwallet.vcxproj.metaproj" (default target) (12) ->
       "C:\projects\turtlecoin\build\src\Crypto.vcxproj" (default target) (14) ->
       (ClCompile target) -> 
         C:\projects\turtlecoin\src\crypto\oaes_lib.c(513): warning C4244: '=': conversion from 'uintptr_t' to 'uint32_t', possible loss of data [C:\projects\turtlecoin\build\src\Crypto.vcxproj]
         C:\projects\turtlecoin\src\crypto\oaes_lib.c(710): warning C4267: '=': conversion from 'size_t' to 'uint8_t', possible loss of data [C:\projects\turtlecoin\build\src\Crypto.vcxproj]
         C:\projects\turtlecoin\src\crypto\oaes_lib.c(1303): warning C4267: '=': conversion from 'size_t' to 'uint8_t', possible loss of data [C:\projects\turtlecoin\build\src\Crypto.vcxproj]
       "C:\projects\turtlecoin\build\TurtleCoin.sln" (default target) (1) ->
       "C:\projects\turtlecoin\build\src\zedwallet.vcxproj.metaproj" (default target) (12) ->
       "C:\projects\turtlecoin\build\src\Common.vcxproj" (default target) (13) ->
       (Lib target) -> 
         FileMappedVector.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library [C:\projects\turtlecoin\build\src\Common.vcxproj]
       "C:\projects\turtlecoin\build\TurtleCoin.sln" (default target) (1) ->
       "C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj.metaproj" (default target) (10) ->
       "C:\projects\turtlecoin\build\external\rocksdb\build_version.vcxproj" (default target) (27) ->
       (ClCompile target) -> 
         cl : Command line warning D9002: ignoring unknown option '-fno-rtti' [C:\projects\turtlecoin\build\external\rocksdb\build_version.vcxproj]
       "C:\projects\turtlecoin\build\TurtleCoin.sln" (default target) (1) ->
       "C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj.metaproj" (default target) (10) ->
       "C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj" (default target) (28) ->
         cl : Command line warning D9002: ignoring unknown option '-fno-rtti' [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         cl : Command line warning D9002: ignoring unknown option '-fno-rtti' [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         cl : Command line warning D9002: ignoring unknown option '-fno-rtti' [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
       "C:\projects\turtlecoin\build\TurtleCoin.sln" (default target) (1) ->
       "C:\projects\turtlecoin\build\src\CryptoNoteCore.vcxproj.metaproj" (default target) (3) ->
       "C:\projects\turtlecoin\build\src\P2P.vcxproj.metaproj" (default target) (4) ->
       "C:\projects\turtlecoin\build\src\P2P.vcxproj" (default target) (29) ->
       (Lib target) -> 
         IP2pNodeInternal.obj : warning LNK4221: This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library [C:\projects\turtlecoin\build\src\P2P.vcxproj]
       "C:\projects\turtlecoin\build\TurtleCoin.sln" (default target) (1) ->
       "C:\projects\turtlecoin\build\src\CryptoNoteCore.vcxproj.metaproj" (default target) (3) ->
       "C:\projects\turtlecoin\build\src\CryptoNoteCore.vcxproj" (default target) (30) ->
       (ClCompile target) -> 
         C:\projects\turtlecoin\src\CryptoNoteCore\Checkpoints.cpp(54): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\projects\turtlecoin\build\src\CryptoNoteCore.vcxproj]
         C:\projects\turtlecoin\src\CryptoNoteCore\Core.cpp(1174): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [C:\projects\turtlecoin\build\src\CryptoNoteCore.vcxproj]
       "C:\projects\turtlecoin\build\TurtleCoin.sln" (default target) (1) ->
       "C:\projects\turtlecoin\build\src\zedwallet.vcxproj.metaproj" (default target) (12) ->
       "C:\projects\turtlecoin\build\src\zedwallet.vcxproj" (default target) (34) ->
         C:\projects\turtlecoin\src\zedwallet\Transfer.cpp(646): warning C5030: attribute 'fallthrough' is not recognized [C:\projects\turtlecoin\build\src\zedwallet.vcxproj]
       "C:\projects\turtlecoin\build\TurtleCoin.sln" (default target) (1) ->
       "C:\projects\turtlecoin\build\src\WalletService.vcxproj.metaproj" (default target) (8) ->
       "C:\projects\turtlecoin\build\src\WalletService.vcxproj" (default target) (21) ->
       (ClCompile target) -> 
         C:\projects\turtlecoin\src\WalletService\ConfigurationManager.cpp(25): fatal error C1083: Cannot open include file: 'version.h': No such file or directory [C:\projects\turtlecoin\build\src\WalletService.vcxproj]
         C:\projects\turtlecoin\src\WalletService\main.cpp(25): fatal error C1083: Cannot open include file: 'version.h': No such file or directory [C:\projects\turtlecoin\build\src\WalletService.vcxproj]
       "C:\projects\turtlecoin\build\TurtleCoin.sln" (default target) (1) ->
       "C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj.metaproj" (default target) (10) ->
       "C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj" (default target) (28) ->
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(988): error C2065: 'STORAGE_PROPERTY_QUERY': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(988): error C2146: syntax error: missing ';' before identifier 'spropertyquery' [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(988): error C2065: 'spropertyquery': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(989): error C2065: 'spropertyquery': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(989): error C2228: left of '.PropertyId' must have class/struct/union [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(989): error C2065: 'StorageAccessAlignmentProperty': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(990): error C2065: 'spropertyquery': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(990): error C2228: left of '.QueryType' must have class/struct/union [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(990): error C2065: 'PropertyStandardQuery': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(992): error C2065: 'STORAGE_ACCESS_ALIGNMENT_DESCRIPTOR': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(995): error C2065: 'IOCTL_STORAGE_QUERY_PROPERTY': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(996): error C2065: 'spropertyquery': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(997): error C2065: 'STORAGE_ACCESS_ALIGNMENT_DESCRIPTOR': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1000): error C2065: 'STORAGE_ACCESS_ALIGNMENT_DESCRIPTOR': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1000): error C2059: syntax error: ')' [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1005): error C2065: 'DISK_GEOMETRY_EX': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1005): error C2146: syntax error: missing ';' before identifier 'geometry' [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1005): error C2065: 'geometry': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1006): error C2065: 'IOCTL_DISK_GET_DRIVE_GEOMETRY': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1007): error C2065: 'geometry': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1009): error C2065: 'geometry': undeclared identifier [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1009): error C2228: left of '.Geometry' must have class/struct/union [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
         c:\projects\turtlecoin\external\rocksdb\port\win\env_win.cc(1009): error C2228: left of '.BytesPerSector' must have class/struct/union [C:\projects\turtlecoin\build\external\rocksdb\rocksdb.vcxproj]
    12 Warning(s)
    25 Error(s)
Time Elapsed 00:16:15.80
Command exited with code 1```

**Comment by ZedPea** [comment]
shhh

**Comment by RocksteadyTC** [comment]
brrrrap

**Comment by brandonlehmann** [comment]
Did you just merge this when it won't compile? @RocksteadyTC

**Comment by RocksteadyTC** [comment]
what you gonna do about it OFFICER

**Comment by fexra** [comment]
:disappointed_relieved:

**Comment by RocksteadyTC** [comment]
It works on Linux over here

**Comment by fexra** [comment]
wangblows

**Comment by brandonlehmann** [comment]
Make sure it goes in the release notes that Windows:tm: users are out of luck in the next release.

**Comment by RocksteadyTC** [comment]
If we get pushed to make a release for windows users before it's fixed, we can roll that one commit back

**Comment by brandonlehmann** [comment]
Why can't you just let me throw my tantrum? lol

**Comment by bobbieltd** [comment]
+1
In my observation,  turtlecoin database is big now and it often struggles in one CPU core.
My suggestion is to increase the values in src/CryptoNoteCore/DataBaseConfig.cpp

read buffer from 10 Mb —> 512 Mb
max background thread 2 —> 4 or number of cores (bu default, one is compaction thread and the rest are write threads with low priority so it won’t impact PC performance but still avoid write stall and congestion )

**Pull request merged**
