### PR TITLE
that's a big buffer

### PR DESCRIPTION
**Pull request by zpalmtree**
We weren't using megabytes when loading the default values, so we had a buffer of 256/10 bytes, lol

### CODE REVIEW

**Comment by brandonlehmann** [comment]
You need to update the config and cli parsers to convert the MB values to byte sizes then :)

**Comment by zpalmtree** [comment]
out of scope

**Comment by brandonlehmann** [comment]
Negative ghost writer. It's well within scope.

**Comment by zpalmtree** [comment]
Updated

**Pull request merged**
