### PR TITLE
Moving /queryblocksdetailed behind a separate cli flag

### PR DESCRIPTION
**Pull request by brandonlehmann**

### CODE REVIEW

**Comment by DroppingThePacketsHard** [comment]
Why? Does this have any purpose?

**Comment by brandonlehmann** [comment]
> Why? Does this have any purpose?

Wouldn’t have submitted it if it didn’t have a purpose :)

**Comment by DroppingThePacketsHard** [comment]
I don't like to have to type more than I need 😄

**Comment by 0des** [comment]
You also don't seem to like to read. This commit looks similar to other work we've seen recently. Hmm.

**Comment by brandonlehmann** [comment]
> I don't like to have to type more than I need 😄

Use config files.

**Comment by DroppingThePacketsHard** [comment]
> Use config files.
Aight, will do that 👍

**Pull request merged**
