### PR TITLE
Walletgreen rewrite

### PR DESCRIPTION
**Pull request by zpalmtree**
Note: Breaks current wallet syncing due to some modifications in how core.cpp returns blocks - wallet syncing works correctly in the rewrite.

### CODE REVIEW

**Comment by brandonlehmann** [comment]
Added WIP to title — @RocksteadyTC that means don’t just go merging stuff. 

Added labels that felt relevant.

**Comment by zpalmtree** [comment]
It's on a branch so merge should be OK - should probably find out how to get cryptoPP working on appveyor and travis though. I hope it's easy to get working on windows...

**Comment by brandonlehmann** [comment]
Ah... I missed that. Why not just push it to the branch then?

**Comment by zpalmtree** [comment]
idk, just wanted to check it was OK first, gives an opportunity for code review if desired. I forgot about cryptoPP, I'd like to get a build process documented so if someone does want to test/help they know how.

**Comment by brandonlehmann** [comment]
Also... recommend including cryptopp source and compile at build time. Finding the package on windows is likely a non-starter.

**Comment by brandonlehmann** [comment]
Cross linked comments. Lol.

**Pull request merged**
