### PR TITLE
replace "bc_height" with "status" as commands have changed

### PR DESCRIPTION
**Pull request by plenteum**
just updating the info message to match the available commands with the latest updates

### CODE REVIEW

**Comment by brandonlehmann** [comment]
@plenteum good catch!

**Comment by RocksteadyTC** [comment]
I think this is the first fork to contribute something upstream. Do you concur? @brandonlehmann @ZedPea

**Comment by brandonlehmann** [comment]
In my humble opinion. Yes.

**Comment by plenteum** [comment]
Thanks guys, hopefully I will have more to contribute down the line as this was just a really small thing I noticed.

**Pull request merged**
