### PR TITLE
Improve static assert compatibility for Linux

### PR DESCRIPTION
**Pull request by gxhshw**

### CODE REVIEW

**Comment by RocksteadyTC** [comment]
Hello @gxhshw thanks for contributing your first PR :) Can you tell me more about this?

**Comment by gxhshw** [comment]
Hi @RocksteadyTC , I think this will improve the compatibility of static_assert on Linux. I experienced static_assert error when building turtlecoin binaries for Centos 6.5 x86_64, even after I changed '#include "../Common/static_assert.h"' to '#include "Common/static_assert.h"' in src/crypto/hash-ops.h. I'm not an expert, with my limited knowledge I'm just want to to share what I've found. :)

**Comment by RocksteadyTC** [comment]
Congratulations on your first PR merge, thank you for contributing! Are you in the Discord server?

**Comment by gxhshw** [comment]
Thanks. No problem at all.
Yes, I'm using username: weiven in Discord.
Just additional info.. I tried to build this version turtlecoin binaries using gcc 6.3.1 , Centos's devtoolset-6.

**Pull request merged**
