### PR TITLE
Better error message if readline already depended on

### PR DESCRIPTION
**Pull request by ZedPea**

### CODE REVIEW

**Comment by ZedPea** [comment]
Don't merge, I'm gonna try and get readline compiling statically.

**Comment by RocksteadyTC** [comment]
How we doin @ZedPea

**Comment by ZedPea** [comment]
I think that means I did it right

```
[src]λ ldd TurtleCoind 
	linux-vdso.so.1 (0x00007ffe2925e000)
	libreadline.so.7 => /usr/lib/libreadline.so.7 (0x00007ff2acaab000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007ff2ac8a3000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007ff2ac50e000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007ff2ac2f0000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007ff2abf34000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007ff2ad63b000)
	libncursesw.so.6 => /usr/lib/libncursesw.so.6 (0x00007ff2abcc7000)
[src]λ ldd TurtleCoind 
	linux-vdso.so.1 (0x00007ffd185e4000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f3753865000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f37534d0000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f37532b2000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f3752ef6000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f37543b0000)
```

Just need to fix the merge conflicts now.

**Comment by ZedPea** [comment]
I think this is OK to merge now. If someone with a faster machine could verify that -DENABLE_READLINE=FALSE correctly disables readline in zedwallet, that would be good, my machine is taking sooo long to build rn

**Comment by ZedPea** [comment]
No wait, I fucked it up, lol

**Comment by ZedPea** [comment]
Probably good now, but don't have time to test :/

**Pull request merged**
