### PR TITLE
Slight path tweaks to prevent 'duplicate' swagger paths

### PR DESCRIPTION
**Pull request by zpalmtree**
I was doing swagger query parameters wrong (using `[]` instead of `{}`) to indicate parameters that are part of the URL. Once fixed, swagger couldn't figure out that the paths would be different, for example,
`/transactions/{hash}` vs `/transactions/{address}`.

So, just added a small amount to the path to fix any conflicts.

Swagger updates: https://github.com/zpalmtree/wallet-api-docs/commit/2d90804182c08b955e2f4bab3ff3e0457ead1632

Updated site: https://www.futuregadget.xyz/api-docs/

### CODE REVIEW

**Comment by zpalmtree** [comment]
Slightly related note: I haven't updated the swagger.yaml included in the WalletApi folder - I think it can be tracked by my [wallet-api-docs repo](https://github.com/zpalmtree/wallet-api-docs) instead, and we can remove it here.

I'd like to add this repo under the TurtleCoin Github if no-one has any issues with how it looks - [preview](https://www.futuregadget.xyz/api-docs/)

**Comment by zpalmtree** [comment]
Don't merge this, I forgot to remove the changed path when grabbing the path elements. Will fix tomorrow

**Comment by zpalmtree** [comment]
Fixed

**Comment by RocksteadyTC** [comment]
ready?

**Comment by zpalmtree** [comment]
Wait for the green checkmark :)

**Comment by RocksteadyTC** [comment]
🍿

**Comment by brandonlehmann** [comment]
:)

**Pull request merged**
